version: 2.0
logger:
  level: INFO
  debug_file: 'debug.log'
  format: '%(asctime)-15s %(name)s %(message)s'
plc:
  ip: 192.168.99.81 # PLC SIM ip adress
  db_num: 1 # DB1 Don't forget to turn off optimezed block access! Settings - attributes
  reconnect_timeout: 60
  refresh_time: 1.5
krc_rpc:
  hostname: 'PCRC-2RL7HHTTRE' # OfficeLite PC's hostname
  port: 3333 # must be same as in appsettings.json (listen port KRC-RPC)
  authkey: 'TOP_SECRET_KEY' # must be same as in appsettings.json (auth key KRC-RPC)
  reconnect_timeout: 10
  refresh_time: 1.5
robodk:
  robotname: 'KUKA KR 50 R2100' # Must be same as the robot's name in RoboDK station
  CNT: 10 # Also known as: CNT, APO/C_DIS, ZoneData, Blending radius, cornering
  speed: 1000 # Set linear speed in mm/s
  refresh_time: 1.5